apiVersion: backplane.open-cluster-management.io/v1alpha1
kind: BackplaneConfig
metadata:
  name: backplaneconfig-sample
spec:
  # Add fields here
  foo: bar
  nodeSelector: 
    type: test
  imagePullSecret: test